import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='flex gap-5 p-8'>
          <Link className='text-blue-700' href='/'>Casa</Link>
          <Link className='text-blue-700' href='/personajes'>Personajes</Link>
          <Link className='text-blue-700' href='/episodios'>Episodios</Link>
          <Link className='text-blue-700' href='/locaciones'>Locaciones</Link>
        </header>
        {children}
      </body>
    </html>
  )
}
